---
# Use the Cornix board definitions provided by furugo-dev/zmk-keyboard-cornix.
include:
  - board: cornix_left
    artifact-name: cornix_left

  - board: cornix_right
    artifact-name: cornix_right

  - board: cornix_right
    shield: settings_reset
    artifact-name: reset
